//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.QueueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue_clinictype", Namespace="http://schemas.datacontract.org/2004/07/Queue.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class queue_clinictype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> clinictype_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> clinictype_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clinictype_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> del_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_sortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> clinictype_group {
            get {
                return this.clinictype_groupField;
            }
            set {
                if ((this.clinictype_groupField.Equals(value) != true)) {
                    this.clinictype_groupField = value;
                    this.RaisePropertyChanged("clinictype_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> clinictype_key {
            get {
                return this.clinictype_keyField;
            }
            set {
                if ((this.clinictype_keyField.Equals(value) != true)) {
                    this.clinictype_keyField = value;
                    this.RaisePropertyChanged("clinictype_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clinictype_name {
            get {
                return this.clinictype_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.clinictype_nameField, value) != true)) {
                    this.clinictype_nameField = value;
                    this.RaisePropertyChanged("clinictype_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> del_flag {
            get {
                return this.del_flagField;
            }
            set {
                if ((this.del_flagField.Equals(value) != true)) {
                    this.del_flagField = value;
                    this.RaisePropertyChanged("del_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_code {
            get {
                return this.queue_codeField;
            }
            set {
                if ((this.queue_codeField.Equals(value) != true)) {
                    this.queue_codeField = value;
                    this.RaisePropertyChanged("queue_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_sort {
            get {
                return this.queue_sortField;
            }
            set {
                if ((this.queue_sortField.Equals(value) != true)) {
                    this.queue_sortField = value;
                    this.RaisePropertyChanged("queue_sort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue_config_sys", Namespace="http://schemas.datacontract.org/2004/07/Queue.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class queue_config_sys : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string config_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> config_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string config_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string config_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string config_valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> del_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> update_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string config_desc {
            get {
                return this.config_descField;
            }
            set {
                if ((object.ReferenceEquals(this.config_descField, value) != true)) {
                    this.config_descField = value;
                    this.RaisePropertyChanged("config_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> config_group {
            get {
                return this.config_groupField;
            }
            set {
                if ((this.config_groupField.Equals(value) != true)) {
                    this.config_groupField = value;
                    this.RaisePropertyChanged("config_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string config_key {
            get {
                return this.config_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.config_keyField, value) != true)) {
                    this.config_keyField = value;
                    this.RaisePropertyChanged("config_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string config_name {
            get {
                return this.config_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.config_nameField, value) != true)) {
                    this.config_nameField = value;
                    this.RaisePropertyChanged("config_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string config_value {
            get {
                return this.config_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.config_valueField, value) != true)) {
                    this.config_valueField = value;
                    this.RaisePropertyChanged("config_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> del_flag {
            get {
                return this.del_flagField;
            }
            set {
                if ((this.del_flagField.Equals(value) != true)) {
                    this.del_flagField = value;
                    this.RaisePropertyChanged("del_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> update_date {
            get {
                return this.update_dateField;
            }
            set {
                if ((this.update_dateField.Equals(value) != true)) {
                    this.update_dateField = value;
                    this.RaisePropertyChanged("update_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue_order_info", Namespace="http://schemas.datacontract.org/2004/07/Queue.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class queue_order_info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> XGRQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YXBZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string csrqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hosNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hosOrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userCardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> XGRQ {
            get {
                return this.XGRQField;
            }
            set {
                if ((this.XGRQField.Equals(value) != true)) {
                    this.XGRQField = value;
                    this.RaisePropertyChanged("XGRQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YXBZ {
            get {
                return this.YXBZField;
            }
            set {
                if ((object.ReferenceEquals(this.YXBZField, value) != true)) {
                    this.YXBZField = value;
                    this.RaisePropertyChanged("YXBZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string csrq {
            get {
                return this.csrqField;
            }
            set {
                if ((object.ReferenceEquals(this.csrqField, value) != true)) {
                    this.csrqField = value;
                    this.RaisePropertyChanged("csrq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.endTimeField, value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hosName {
            get {
                return this.hosNameField;
            }
            set {
                if ((object.ReferenceEquals(this.hosNameField, value) != true)) {
                    this.hosNameField = value;
                    this.RaisePropertyChanged("hosName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hosOrgCode {
            get {
                return this.hosOrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.hosOrgCodeField, value) != true)) {
                    this.hosOrgCodeField = value;
                    this.RaisePropertyChanged("hosOrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderDate {
            get {
                return this.orderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDateField, value) != true)) {
                    this.orderDateField = value;
                    this.RaisePropertyChanged("orderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.orderIdField, value) != true)) {
                    this.orderIdField = value;
                    this.RaisePropertyChanged("orderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.startTimeField, value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userCardId {
            get {
                return this.userCardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userCardIdField, value) != true)) {
                    this.userCardIdField = value;
                    this.RaisePropertyChanged("userCardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userCardType {
            get {
                return this.userCardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.userCardTypeField, value) != true)) {
                    this.userCardTypeField = value;
                    this.RaisePropertyChanged("userCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xb {
            get {
                return this.xbField;
            }
            set {
                if ((object.ReferenceEquals(this.xbField, value) != true)) {
                    this.xbField = value;
                    this.RaisePropertyChanged("xb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue_takeno", Namespace="http://schemas.datacontract.org/2004/07/Queue.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class queue_takeno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> call_shareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> call_station_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> call_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> clinictype_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> del_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queue_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_takeno_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queue_takeno_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queue_takeno_idcardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_takeno_idcard_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> queue_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> sort_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> takeno_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> takeno_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> takeno_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> update_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string call_name {
            get {
                return this.call_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.call_nameField, value) != true)) {
                    this.call_nameField = value;
                    this.RaisePropertyChanged("call_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> call_share {
            get {
                return this.call_shareField;
            }
            set {
                if ((this.call_shareField.Equals(value) != true)) {
                    this.call_shareField = value;
                    this.RaisePropertyChanged("call_share");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> call_station_id {
            get {
                return this.call_station_idField;
            }
            set {
                if ((this.call_station_idField.Equals(value) != true)) {
                    this.call_station_idField = value;
                    this.RaisePropertyChanged("call_station_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> call_time {
            get {
                return this.call_timeField;
            }
            set {
                if ((this.call_timeField.Equals(value) != true)) {
                    this.call_timeField = value;
                    this.RaisePropertyChanged("call_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> clinictype_key {
            get {
                return this.clinictype_keyField;
            }
            set {
                if ((this.clinictype_keyField.Equals(value) != true)) {
                    this.clinictype_keyField = value;
                    this.RaisePropertyChanged("clinictype_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> del_flag {
            get {
                return this.del_flagField;
            }
            set {
                if ((this.del_flagField.Equals(value) != true)) {
                    this.del_flagField = value;
                    this.RaisePropertyChanged("del_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_idField, value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queue_name {
            get {
                return this.queue_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.queue_nameField, value) != true)) {
                    this.queue_nameField = value;
                    this.RaisePropertyChanged("queue_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_takeno_code {
            get {
                return this.queue_takeno_codeField;
            }
            set {
                if ((this.queue_takeno_codeField.Equals(value) != true)) {
                    this.queue_takeno_codeField = value;
                    this.RaisePropertyChanged("queue_takeno_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queue_takeno_id {
            get {
                return this.queue_takeno_idField;
            }
            set {
                if ((object.ReferenceEquals(this.queue_takeno_idField, value) != true)) {
                    this.queue_takeno_idField = value;
                    this.RaisePropertyChanged("queue_takeno_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queue_takeno_idcard {
            get {
                return this.queue_takeno_idcardField;
            }
            set {
                if ((object.ReferenceEquals(this.queue_takeno_idcardField, value) != true)) {
                    this.queue_takeno_idcardField = value;
                    this.RaisePropertyChanged("queue_takeno_idcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_takeno_idcard_type {
            get {
                return this.queue_takeno_idcard_typeField;
            }
            set {
                if ((this.queue_takeno_idcard_typeField.Equals(value) != true)) {
                    this.queue_takeno_idcard_typeField = value;
                    this.RaisePropertyChanged("queue_takeno_idcard_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> queue_type {
            get {
                return this.queue_typeField;
            }
            set {
                if ((this.queue_typeField.Equals(value) != true)) {
                    this.queue_typeField = value;
                    this.RaisePropertyChanged("queue_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> sort_num {
            get {
                return this.sort_numField;
            }
            set {
                if ((this.sort_numField.Equals(value) != true)) {
                    this.sort_numField = value;
                    this.RaisePropertyChanged("sort_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> takeno_state {
            get {
                return this.takeno_stateField;
            }
            set {
                if ((this.takeno_stateField.Equals(value) != true)) {
                    this.takeno_stateField = value;
                    this.RaisePropertyChanged("takeno_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> takeno_time {
            get {
                return this.takeno_timeField;
            }
            set {
                if ((this.takeno_timeField.Equals(value) != true)) {
                    this.takeno_timeField = value;
                    this.RaisePropertyChanged("takeno_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> takeno_type {
            get {
                return this.takeno_typeField;
            }
            set {
                if ((this.takeno_typeField.Equals(value) != true)) {
                    this.takeno_typeField = value;
                    this.RaisePropertyChanged("takeno_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> update_date {
            get {
                return this.update_dateField;
            }
            set {
                if ((this.update_dateField.Equals(value) != true)) {
                    this.update_dateField = value;
                    this.RaisePropertyChanged("update_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue_takeno_middle", Namespace="http://schemas.datacontract.org/2004/07/Queue.Service.Entity")]
    [System.SerializableAttribute()]
    public partial class queue_takeno_middle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queue_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> update_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCard {
            get {
                return this.IdCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCardField, value) != true)) {
                    this.IdCardField = value;
                    this.RaisePropertyChanged("IdCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalCard {
            get {
                return this.MedicalCardField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicalCardField, value) != true)) {
                    this.MedicalCardField = value;
                    this.RaisePropertyChanged("MedicalCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string queue_state {
            get {
                return this.queue_stateField;
            }
            set {
                if ((object.ReferenceEquals(this.queue_stateField, value) != true)) {
                    this.queue_stateField = value;
                    this.RaisePropertyChanged("queue_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> update_date {
            get {
                return this.update_dateField;
            }
            set {
                if ((this.update_dateField.Equals(value) != true)) {
                    this.update_dateField = value;
                    this.RaisePropertyChanged("update_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueueService.IQueueService")]
    public interface IQueueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Test", ReplyAction="http://tempuri.org/IQueueService/TestResponse")]
        void Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/TakenoApi", ReplyAction="http://tempuri.org/IQueueService/TakenoApiResponse")]
        string TakenoApi(int takenoType, string barCode, string takenoCode, string name, string callName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueClinicTypeList", ReplyAction="http://tempuri.org/IQueueService/GetQueueClinicTypeListResponse")]
        Order.QueueService.queue_clinictype[] GetQueueClinicTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetClinicTypeName", ReplyAction="http://tempuri.org/IQueueService/GetClinicTypeNameResponse")]
        string GetClinicTypeName(string clinicTypeKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueConfigSysList", ReplyAction="http://tempuri.org/IQueueService/GetQueueConfigSysListResponse")]
        Order.QueueService.queue_config_sys[] GetQueueConfigSysList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/SetQueueConfigSys", ReplyAction="http://tempuri.org/IQueueService/SetQueueConfigSysResponse")]
        int SetQueueConfigSys(Order.QueueService.queue_config_sys qcs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/PullOrderService", ReplyAction="http://tempuri.org/IQueueService/PullOrderServiceResponse")]
        string PullOrderService(string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueOrderInfo", ReplyAction="http://tempuri.org/IQueueService/GetQueueOrderInfoResponse")]
        Order.QueueService.queue_order_info GetQueueOrderInfo(string userCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/SetQueueOrderInfo", ReplyAction="http://tempuri.org/IQueueService/SetQueueOrderInfoResponse")]
        void SetQueueOrderInfo(Order.QueueService.queue_order_info queueOrderInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetName", ReplyAction="http://tempuri.org/IQueueService/GetNameResponse")]
        string GetName(string barCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetDateTime", ReplyAction="http://tempuri.org/IQueueService/GetDateTimeResponse")]
        System.DateTime GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/TakeNo", ReplyAction="http://tempuri.org/IQueueService/TakeNoResponse")]
        Order.QueueService.queue_takeno TakeNo(Order.QueueService.queue_takeno queueTakeno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/CallNo", ReplyAction="http://tempuri.org/IQueueService/CallNoResponse")]
        Order.QueueService.queue_takeno CallNo(Order.QueueService.queue_takeno queueTakeno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/OverNo", ReplyAction="http://tempuri.org/IQueueService/OverNoResponse")]
        Order.QueueService.queue_takeno OverNo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/ResNo", ReplyAction="http://tempuri.org/IQueueService/ResNoResponse")]
        Order.QueueService.queue_takeno ResNo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueTakeno", ReplyAction="http://tempuri.org/IQueueService/GetQueueTakenoResponse")]
        Order.QueueService.queue_takeno GetQueueTakeno(Order.QueueService.queue_takeno queueTakeno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueTakenoList", ReplyAction="http://tempuri.org/IQueueService/GetQueueTakenoListResponse")]
        Order.QueueService.queue_takeno[] GetQueueTakenoList(Order.QueueService.queue_takeno queueTakeno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetQueueTakenoMiddle", ReplyAction="http://tempuri.org/IQueueService/GetQueueTakenoMiddleResponse")]
        Order.QueueService.queue_takeno_middle GetQueueTakenoMiddle(Order.QueueService.queue_takeno_middle queueTakenoMiddle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueServiceChannel : Order.QueueService.IQueueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueServiceClient : System.ServiceModel.ClientBase<Order.QueueService.IQueueService>, Order.QueueService.IQueueService {
        
        public QueueServiceClient() {
        }
        
        public QueueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Test() {
            base.Channel.Test();
        }
        
        public string TakenoApi(int takenoType, string barCode, string takenoCode, string name, string callName) {
            return base.Channel.TakenoApi(takenoType, barCode, takenoCode, name, callName);
        }
        
        public Order.QueueService.queue_clinictype[] GetQueueClinicTypeList() {
            return base.Channel.GetQueueClinicTypeList();
        }
        
        public string GetClinicTypeName(string clinicTypeKey) {
            return base.Channel.GetClinicTypeName(clinicTypeKey);
        }
        
        public Order.QueueService.queue_config_sys[] GetQueueConfigSysList() {
            return base.Channel.GetQueueConfigSysList();
        }
        
        public int SetQueueConfigSys(Order.QueueService.queue_config_sys qcs) {
            return base.Channel.SetQueueConfigSys(qcs);
        }
        
        public string PullOrderService(string time) {
            return base.Channel.PullOrderService(time);
        }
        
        public Order.QueueService.queue_order_info GetQueueOrderInfo(string userCardId) {
            return base.Channel.GetQueueOrderInfo(userCardId);
        }
        
        public void SetQueueOrderInfo(Order.QueueService.queue_order_info queueOrderInfo) {
            base.Channel.SetQueueOrderInfo(queueOrderInfo);
        }
        
        public string GetName(string barCode) {
            return base.Channel.GetName(barCode);
        }
        
        public System.DateTime GetDateTime() {
            return base.Channel.GetDateTime();
        }
        
        public Order.QueueService.queue_takeno TakeNo(Order.QueueService.queue_takeno queueTakeno) {
            return base.Channel.TakeNo(queueTakeno);
        }
        
        public Order.QueueService.queue_takeno CallNo(Order.QueueService.queue_takeno queueTakeno) {
            return base.Channel.CallNo(queueTakeno);
        }
        
        public Order.QueueService.queue_takeno OverNo(string id) {
            return base.Channel.OverNo(id);
        }
        
        public Order.QueueService.queue_takeno ResNo(string id) {
            return base.Channel.ResNo(id);
        }
        
        public Order.QueueService.queue_takeno GetQueueTakeno(Order.QueueService.queue_takeno queueTakeno) {
            return base.Channel.GetQueueTakeno(queueTakeno);
        }
        
        public Order.QueueService.queue_takeno[] GetQueueTakenoList(Order.QueueService.queue_takeno queueTakeno) {
            return base.Channel.GetQueueTakenoList(queueTakeno);
        }
        
        public Order.QueueService.queue_takeno_middle GetQueueTakenoMiddle(Order.QueueService.queue_takeno_middle queueTakenoMiddle) {
            return base.Channel.GetQueueTakenoMiddle(queueTakenoMiddle);
        }
    }
}
