//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ztest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUser", Namespace="http://tempuri.org/", ItemName="user")]
    [System.SerializableAttribute()]
    public class ArrayOfUser : System.Collections.Generic.List<Ztest.ServiceReference1.user> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WsSoap")]
    public interface WsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTime", ReplyAction="*")]
        System.DateTime GetTime();
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 u 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        Ztest.ServiceReference1.InsertResponse Insert(Ztest.ServiceReference1.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 u 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Ztest.ServiceReference1.UpdateResponse Update(Ztest.ServiceReference1.UpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        Ztest.ServiceReference1.SelectResponse Select(Ztest.ServiceReference1.SelectRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SelectAllResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        Ztest.ServiceReference1.SelectAllResponse SelectAll(Ztest.ServiceReference1.SelectAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        void Test();
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestStr", ReplyAction="*")]
        Ztest.ServiceReference1.TestStrResponse TestStr(Ztest.ServiceReference1.TestStrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(Ztest.ServiceReference1.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ztest.ServiceReference1.user u;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(Ztest.ServiceReference1.user u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(Ztest.ServiceReference1.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(bool InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Ztest.ServiceReference1.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ztest.ServiceReference1.user u;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Ztest.ServiceReference1.user u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Ztest.ServiceReference1.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Ztest.ServiceReference1.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(int id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Ztest.ServiceReference1.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ztest.ServiceReference1.ArrayOfUser SelectResult;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(Ztest.ServiceReference1.ArrayOfUser SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.SelectAllRequestBody Body;
        
        public SelectAllRequest() {
        }
        
        public SelectAllRequest(Ztest.ServiceReference1.SelectAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllRequestBody {
        
        public SelectAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.SelectAllResponseBody Body;
        
        public SelectAllResponse() {
        }
        
        public SelectAllResponse(Ztest.ServiceReference1.SelectAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ztest.ServiceReference1.ArrayOfUser SelectAllResult;
        
        public SelectAllResponseBody() {
        }
        
        public SelectAllResponseBody(Ztest.ServiceReference1.ArrayOfUser SelectAllResult) {
            this.SelectAllResult = SelectAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStr", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.TestStrRequestBody Body;
        
        public TestStrRequest() {
        }
        
        public TestStrRequest(Ztest.ServiceReference1.TestStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public TestStrRequestBody() {
        }
        
        public TestStrRequestBody(int id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStrResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ztest.ServiceReference1.TestStrResponseBody Body;
        
        public TestStrResponse() {
        }
        
        public TestStrResponse(Ztest.ServiceReference1.TestStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestStrResult;
        
        public TestStrResponseBody() {
        }
        
        public TestStrResponseBody(string TestStrResult) {
            this.TestStrResult = TestStrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsSoapChannel : Ztest.ServiceReference1.WsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSoapClient : System.ServiceModel.ClientBase<Ztest.ServiceReference1.WsSoap>, Ztest.ServiceReference1.WsSoap {
        
        public WsSoapClient() {
        }
        
        public WsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetTime() {
            return base.Channel.GetTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ztest.ServiceReference1.InsertResponse Ztest.ServiceReference1.WsSoap.Insert(Ztest.ServiceReference1.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public bool Insert(Ztest.ServiceReference1.user u) {
            Ztest.ServiceReference1.InsertRequest inValue = new Ztest.ServiceReference1.InsertRequest();
            inValue.Body = new Ztest.ServiceReference1.InsertRequestBody();
            inValue.Body.u = u;
            Ztest.ServiceReference1.InsertResponse retVal = ((Ztest.ServiceReference1.WsSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ztest.ServiceReference1.UpdateResponse Ztest.ServiceReference1.WsSoap.Update(Ztest.ServiceReference1.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(Ztest.ServiceReference1.user u) {
            Ztest.ServiceReference1.UpdateRequest inValue = new Ztest.ServiceReference1.UpdateRequest();
            inValue.Body = new Ztest.ServiceReference1.UpdateRequestBody();
            inValue.Body.u = u;
            Ztest.ServiceReference1.UpdateResponse retVal = ((Ztest.ServiceReference1.WsSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ztest.ServiceReference1.SelectResponse Ztest.ServiceReference1.WsSoap.Select(Ztest.ServiceReference1.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public Ztest.ServiceReference1.ArrayOfUser Select(int id, string name) {
            Ztest.ServiceReference1.SelectRequest inValue = new Ztest.ServiceReference1.SelectRequest();
            inValue.Body = new Ztest.ServiceReference1.SelectRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            Ztest.ServiceReference1.SelectResponse retVal = ((Ztest.ServiceReference1.WsSoap)(this)).Select(inValue);
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ztest.ServiceReference1.SelectAllResponse Ztest.ServiceReference1.WsSoap.SelectAll(Ztest.ServiceReference1.SelectAllRequest request) {
            return base.Channel.SelectAll(request);
        }
        
        public Ztest.ServiceReference1.ArrayOfUser SelectAll() {
            Ztest.ServiceReference1.SelectAllRequest inValue = new Ztest.ServiceReference1.SelectAllRequest();
            inValue.Body = new Ztest.ServiceReference1.SelectAllRequestBody();
            Ztest.ServiceReference1.SelectAllResponse retVal = ((Ztest.ServiceReference1.WsSoap)(this)).SelectAll(inValue);
            return retVal.Body.SelectAllResult;
        }
        
        public void Test() {
            base.Channel.Test();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ztest.ServiceReference1.TestStrResponse Ztest.ServiceReference1.WsSoap.TestStr(Ztest.ServiceReference1.TestStrRequest request) {
            return base.Channel.TestStr(request);
        }
        
        public string TestStr(int id, string name) {
            Ztest.ServiceReference1.TestStrRequest inValue = new Ztest.ServiceReference1.TestStrRequest();
            inValue.Body = new Ztest.ServiceReference1.TestStrRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            Ztest.ServiceReference1.TestStrResponse retVal = ((Ztest.ServiceReference1.WsSoap)(this)).TestStr(inValue);
            return retVal.Body.TestStrResult;
        }
    }
}
